version: '3.8'
services:
   dev:
      build:
         context: .
         dockerfile: dev-Dockerfile
      container_name: alaajo-api
      # command: yarn run start:dev
      restart: always
      ports:
         - 5800:5500
      # depends_on:
      #    - postgres
      env_file:
         - .env
      networks:
         - alaajo-network

   redis:
      image: redis:5.0
      restart: always
      environment:
         REDIS_USER: alaajo
      ports:
         - 6379:6379
      networks:
         - alaajo-network

 

#volumes:
   # postgres:
   #    name: alaajo-docker-db

networks:
   alaajo-network:
