version: '1.0'
services:
  api:
    build:
      context: "."
      dockerfile: Dockerfile.Dev
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - etap-test-network

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - etap-test-network

volumes:
  postgres:
    name: prisma-docker-db

networks:
  etap-test-network:
